#Key Bindings Configuration
#Tue Nov 18 15:14:08 GMT+08:00 2025
player1.HARD_DROP=CONTROL
player1.HOLD=SHIFT
player1.LEFT=A
player1.RIGHT=D
player1.ROTATE=W
player1.SOFT_DROP=S
player2.HARD_DROP=COMMA
player2.HOLD=PERIOD
player2.LEFT=LEFT
player2.RIGHT=RIGHT
player2.ROTATE=UP
player2.SOFT_DROP=DOWN
single.HARD_DROP=SPACE
single.HOLD=C
single.LEFT=LEFT
single.NEW_GAME=N
single.PAUSE=P
single.RIGHT=RIGHT
single.ROTATE=UP
single.SOFT_DROP=DOWN
