#Key Bindings Configuration
#Mon Dec 01 20:49:14 GMT+08:00 2025
player1.HARD_DROP=SPACE
player1.HOLD=CONTROL
player1.LEFT=A
player1.RIGHT=D
player1.ROTATE=W
player1.SOFT_DROP=S
player2.HARD_DROP=ENTER
player2.HOLD=QUOTE
player2.LEFT=LEFT
player2.RIGHT=RIGHT
player2.ROTATE=UP
player2.SOFT_DROP=DOWN
single.HARD_DROP=SPACE
single.HOLD=C
single.LEFT=LEFT
single.NEW_GAME=N
single.PAUSE=P
single.RIGHT=RIGHT
single.ROTATE=UP
single.SOFT_DROP=DOWN
